name: sonata-archives
channels:
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - click==6.7
  - dominate==2.3.1
  - flask==0.12.2
  - flask-bootstrap==3.3.7.1
  - itsdangerous==0.24
  - jinja2==2.10
  - markupsafe==1.0
  - psycopg2==2.7.3.2
  - visitor==0.1.3
  - werkzeug==0.14.1

